swagger: '2.0'
info:
  version: "1.0"
  title: Pandora Puzzle
schemes:
  - http
basePath: /api
host: "localhost:8080"
produces:
  - application/json
consumes:
  - application/json
paths:
  /time:
    get:
      summary: Get remaining time
      operationId: "retrieveTime"
      responses:
        200:
          description: Remaining time
          type: integer
    post:
      summary: Start, stop or restart time
      operationId: "startStopResetTime"
      consumes:
        - application/json
      parameters:
        - in: body
          name: timeStatus
          description: The call to make
          schema:
            $ref: '#/definitions/TimeStatus'
      responses:
        201:
          description: Applied

  /applications/{application_id}:
    get:
      summary: Read application
      description: |
        Returns details about one application
      operationId: "getapplicationID"
      parameters:
        - name: application_id
          in: path
          type: string
          description: ID of the application
          pattern: "^[a-z][a-z0-9-]+$"
          required: true
      responses:
        200:
          description: Details of one application
          schema:
            $ref: '#/definitions/Application'
        404:
          description: Not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Application'

definitions:

  TimeStatus:
    type: object
    properties:
      status:
        type: string
        enum: [start, stop, resume, restart]

  Application:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier
      name:
        type: string
        description: A human-readable name
      team_id:
        type: string
        description: ID of the team, responsible for this application
      description:
        type: string
        description: Purpose of this application
      url:
        type: string
        description: Live URL of the application
      scm_url:
        type: string
        description: URL of SCM repository
      documentation_url:
        type: string
        description: URL of documentation